/* ************************************************************************** */
/*                                                                            */
/*                                                        ::::::::            */
/*   send.c                                             :+:    :+:            */
/*                                                     +:+                    */
/*   By: tblaudez <tblaudez@student.codam.nl>         +#+                     */
/*                                                   +#+                      */
/*   Created: 2021/03/19 13:02:21 by tblaudez      #+#    #+#                 */
/*   Updated: 2021/03/19 14:09:24 by tblaudez      ########   odam.nl         */
/*                                                                            */
/* ************************************************************************** */

#include "ft_ping.h"

#include <stdio.h> // fprintf, printf
#include <unistd.h> // getpid
#include <sys/time.h> // gettimeofday

/* Send ICMP ECHO_REQUEST to host */
void send_echo_request()
{
	ssize_t			size;
	char			buf[g_ping.datalen];
	char			*ptr = buf + ICMPHDR;
	struct icmphdr	*icmp = (struct icmphdr*) buf;


	// IP header is generated by kernel
	// First 8 bytes are ICMP header
	icmp->type = ICMP_ECHO;
	icmp->code = 0;
	icmp->checksum = 0;
	icmp->un.echo.id = getpid();
	icmp->un.echo.sequence = htons(g_ping.ntransmitted + 1);
	
	// If data is large enough, write timestamp
	if (g_ping.flags & RTT) {
		gettimeofday((struct timeval*) ptr, NULL);
		ptr += sizeof(struct timeval);
	}

	// Rest of data is set to arbitrary values
	for (char j = 0x10; ptr != (buf + g_ping.datalen); ptr++, j++) {
		*ptr = j;
	}

	icmp->checksum = in_cksum(icmp, g_ping.datalen);
	
	// Send ECHO_REQUEST to host
	size = sendto(g_ping.sockfd, icmp, g_ping.datalen, 0, &g_ping.addr, g_ping.addrlen);
	
	if (size == -1) {
		fprintf(stderr, "ft_ping: error sending icmp_seq=%hu\n", ntohs(icmp->un.echo.sequence));
		return;
	}
	
	g_ping.ntransmitted++;
}
